import { createSlice, PayloadAction } from "@reduxjs/toolkit";

interface CounterState {
  contributionYear: number;
}

const initialState: CounterState = {
  contributionYear: new Date().getFullYear(),
};

export const uiSlice = createSlice({
  initialState,
  name: "ui",
  reducers: {
    setContributionYear: (state, action: PayloadAction<number>) => {
      state.contributionYear = action.payload;
    },
  },
});

// Action creators are generated by each case reducer function
const { actions, reducer: uiReducer } = uiSlice;
export const { setContributionYear } = actions;

export default uiReducer;
