import { createSlice, PayloadAction } from "@reduxjs/toolkit";

interface CounterState {
  value: number;
}

const initialState: CounterState = {
  value: 0,
};

export const uiSlice = createSlice({
  initialState,
  name: "ui",
  reducers: {
    increment: (state) => {
      state.value += 1;
    },
  },
});

// Action creators are generated by each case reducer function
export const { increment } = uiSlice.actions;

export default uiSlice.reducer;
